"""adiciona consentimento lgpd na fidelidade

Revision ID: 5886eef42677
Revises: d6a9779e7098
Create Date: 2026-06-28 12:29:27.745543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5886eef42677'
down_revision = 'd6a9779e7098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fidelidades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consentimento_lgpd', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('data_consentimento', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fidelidades', schema=None) as batch_op:
        batch_op.drop_column('data_consentimento')
        batch_op.drop_column('consentimento_lgpd')

    # ### end Alembic commands ###
