"""add fidelidade

Revision ID: a2b2981d21c8
Revises: e13229552335
Create Date: 2026-06-18 23:02:26.264646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b2981d21c8'
down_revision = 'e13229552335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fidelidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('pontos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fidelidades')
    # ### end Alembic commands ###
