"""adiciona unidade ao pedido

Revision ID: d6a9779e7098
Revises: 8fcecc23322b
Create Date: 2026-06-27 11:18:43.169822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6a9779e7098'
down_revision = '8fcecc23322b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            'fk_pedidos_unidade_id_unidades',
            'unidades',
            ['unidade_id'],
            ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('unidade_id')

    # ### end Alembic commands ###
