"""adiciona restricoes unicas

Revision ID: ef12e562e10b
Revises: 5886eef42677
Create Date: 2026-06-28 12:56:01.723850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef12e562e10b'
down_revision = '5886eef42677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoques', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_estoques_produto_unidade', ['produto_id', 'unidade_id'])

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_produtos_nome', ['nome'])

    with op.batch_alter_table('unidades', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_unidades_nome_cidade', ['nome', 'cidade'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unidades', schema=None) as batch_op:
        batch_op.drop_constraint('uq_unidades_nome_cidade', type_='unique')

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_constraint('uq_produtos_nome', type_='unique')

    with op.batch_alter_table('estoques', schema=None) as batch_op:
        batch_op.drop_constraint('uq_estoques_produto_unidade', type_='unique')

    # ### end Alembic commands ###
